# This file can be used to install a new conda environment specifically for this
# application, using the following commands (we choose the arbitrary name
# ai lab for that environment here, feel free to pick your own):
#
#   Create Environment:
#   conda env create -n lab10 -f conda-environment.yml
#
#   Activate Environment:
#   conda activate lab10
#
#
channels:
- conda-forge
- defaults
dependencies:
- python=3.7.9
- pip
- pip:
  - importlib-metadata==4.13.0
  - gym==0.26
  - gym[atari,accept-rom-license]
  - torch
  - torchvision
  - torchaudio
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - opencv-python
  - pygame
